### ISSUE TITLE
Fresh installation issues

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [overblog/ThriftBundle#6]
I've checked out the `symfony-standard` repo branch 2.6 in order to play with the ThriftBundle.
After I included the bundle into composer.json, updated the code and added a correct `thrift.config.compiler.path`, the command "app/console cache:clear" failed with this exception:
```
  [UnexpectedValueException]                                                                                                                             
  RecursiveDirectoryIterator::__construct(/home/wicked/Programming/gitolite/thrift/app/cache/dev/thrift):
  failed to open dir: No such file or directory  
```
I think it would be better if the bundle managed to create the dir automatically.

**Comment by AlexeyKupershtokh** [comment]
It's said in the docs that I should specify a service that looks like:
```yml
#app/config/config.yml
    services:
      *service_name*:
        definition: Service
        namespace: ThriftModel\Service
        definitionPath: /PATH/ # Path of the definition
        server: true    # Define if server class will be generated
```
and then run `php app/console thrift:compile CompleteBundleName Service`.
This causes another exception:
```
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                                                                                  
  The definition for "thrift" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child de  
  finitions, please add abstract=true, otherwise specify a class to get rid of this error.                                                                                                            
```
